# Generated by Django 3.2.6 on 2021-08-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_url_app', '0002_alter_album_num_starts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_starts',
            field=models.IntegerField(choices=[(1, 'Worst'), (2, 'ok'), (3, 'nice'), (4, 'Like'), (5, 'Wow')]),
        ),
    ]
