# Generated by Django 3.2.6 on 2021-09-10 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_url_app', '0003_alter_album_num_starts'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='album',
        ),
    ]
