# Generated by Django 3.2.6 on 2021-09-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_url_app', '0004_alter_album_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table=None,
        ),
    ]
